"""create initial market_daily table

Revision ID: 101306015567
Revises: 
Create Date: 2025-12-02 11:39:26.344439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '101306015567'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_daily',
    sa.Column('sugar_close', sa.Float(), nullable=False),
    sa.Column('sugar_open', sa.Float(), nullable=True),
    sa.Column('usd_cny_rate', sa.Float(), nullable=False),
    sa.Column('bdi_index', sa.Float(), nullable=True),
    sa.Column('import_cost_estimate', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('record_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('record_date')
    )
    with op.batch_alter_table('market_daily', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_market_daily_record_date'), ['record_date'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('market_daily', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_market_daily_record_date'))

    op.drop_table('market_daily')
    # ### end Alembic commands ###
